limit_req_zone $binary_remote_addr zone=admin_login:10m rate=10r/m;

server {
    listen 80;
    listen [::]:80;
    server_name bot.steventeng.uk lineb.172-235-214-249.sslip.io;

    client_max_body_size 1m;

    location = /admin/login {
        limit_req zone=admin_login burst=5 nodelay;
        proxy_pass http://127.0.0.1:8000;
        include proxy_params;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        include proxy_params;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
